pcall(function()
	dofile("Unregister.lua")
end)
dofile("Globals.lua")
dofile("Freeslots.lua")
dofile("Specials.lua")
dofile("Colors.lua")
dofile("CustChar.lua")
dofile("WADLoad.lua")
dofile("Functions.lua")
dofile("Actions.lua")
dofile("+Use.lua")
dofile("Commands.lua")
dofile("Hooks.lua")
dofile("Title.lua")
dofile("Definitions/Inventory/Ammo.lua")
dofile("Definitions/Inventory/Weps.lua")
dofile("Definitions/Objects/Deco.lua")
dofile("Definitions/Objects/Artifacts/Invuln.lua")
dofile("Definitions/Objects/Artifacts/Berserk.lua")
dofile("Definitions/Objects/Artifacts/Megasphere.lua")
dofile("Definitions/Objects/Artifacts/Radiation Suit.lua")
dofile("Definitions/Objects/Artifacts/Soulsphere.lua")
dofile("Definitions/Objects/Items/Ammo.lua")
dofile("Definitions/Objects/Items/Armor.lua")
dofile("Definitions/Objects/Items/Health.lua")
dofile("Definitions/Objects/Items/Weapons.lua")
dofile("Definitions/Objects/Keycards/Yellow Key.lua")
dofile("Definitions/Objects/Keycards/Blue Key.lua")
dofile("Definitions/Objects/Keycards/Red Key.lua")
dofile("Definitions/Objects/Monsters/Commander Keen.lua")
dofile("Definitions/Objects/Monsters/Imp.lua")
dofile("Definitions/Objects/Monsters/Zombieman.lua")
dofile("Definitions/Objects/Monsters/Shotgunner.lua")
dofile("Definitions/Objects/Monsters/Chaingunner.lua")
dofile("Definitions/Objects/Monsters/Demon.lua")
dofile("Definitions/Objects/Monsters/SS Guard.lua")
dofile("Definitions/Objects/Monsters/Hell Knight.lua")
dofile("Definitions/Objects/Monsters/Exploding Barrel.lua")
dofile("Definitions/Objects/Monsters/PLACEHOLD/Archvile.lua")
dofile("Definitions/Objects/Monsters/PLACEHOLD/Lost Soul.lua")
dofile("HUD/HUDLib.lua")
dofile("HUD/HUD.lua")
dofile("HUD/Inter.lua")
dofile("HUD/ENDOOM.lua")
dofile("Player/JohnDoom.lua")
dofile("Player/Player.lua")
dofile("Player/IntermissionThinker.lua")
dofile("Player/KeyBoardCheats.lua")